### ISSUE TITLE
Failed to chat after configuring the OpenAI API keys

### ISSUE THREAD

**Issue by wenlzhang** [khoj-ai/khoj#266]
I got the following errors when trying to chat. Searching works as desired.

```
WARNING  WARNING! stop is not default parameter.         openai.py:211
                                        stop was transferred to
                    model_kwargs.
                                        Please confirm that stop is
                    what you intended.
           WARNING  WARNING! api_key is not default parameter.      openai.py:211
                                        api_key was transferred to
                    model_kwargs.
                                        Please confirm that api_key
                    is what you intended.
WARNING  GPT returned invalid JSON. Falling back to using   gpt.py:116
                    user message as search query.
```

**Comment by sabaimran** [comment]
Hey @wenlzhang , could you try another chat query? These are just warnings and I also see them from time to time, but I'm able to chat. Chat API requests to OpenAI might fail, but we can't do much about that for now, sadly.

**Comment by wenlzhang** [comment]
> Chat API requests to OpenAI might fail, but we can't do much about that for now, sadly.

I tried four queries, but only one worked for me. For the other three queries, I got the following reply as the message:
```
Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=10.0)0,1,2,3,4
```

For now, I only have two files in the Obsidian vault, one PDF research article and one Markdown note extracted from a PDF research article.

I also observed the following during the tests:
- In one of the queries, I used the same query as the one for the Obsidian Vault Chat plugin, but it worked for Vault Chat.
- Even though the queries failed, they still used a lot of gpt-3.5-turbo-0613 tokens, more than 100,000 for each query. Is this normal?

**Comment by sabaimran** [comment]
Hmm, good to know. I think we may need to increase our timeout range for queries. Thanks for the helpful context for debugging. Let me address this. I think we should also be able to use chat streaming to help mitigate some of the timeout errors.

Regarding the token usage, that may be because the query still landed on OpenAI, but it didn't return a response within the waiting window.

**Comment by debanjum** [comment]
> For now, I only have two files in the Obsidian vault, one PDF research article and one Markdown note extracted from a PDF research article.

> Even though the queries failed, they still used a lot of gpt-3.5-turbo-0613 tokens, more than 100,000 for each query. Is this normal?

Yeah, it is not normal to use 100K tokens for each query. I'd suspect you're hitting this issue because the Markdown note extracted from the PDF research article would have no markdown sections (i.e `#` separated headings) ? 

This will result in the complete article being sent to OpenAI for chat processing and consume a lot of tokens every time.
This could also be the reason the chat responses from OpenAI are timing out as ChatGPT is getting a big blob of text to process.

**Comment by wenlzhang** [comment]
> Yeah, it is not normal to use 100K tokens for each query. I'd suspect you're hitting this issue because the Markdown note extracted from the PDF research article would have no markdown sections (i.e `#` separated headings) ?

Sorry, I had a typo. It should be 10K tokens instead of 100K tokens. On the other hand, it is true that there are no markdown sections in the extracted Markdown note. Is there any way to address this? For instance, only a few selected pieces of text that are relevant to the query are sent to OpenAI?

**Comment by debanjum** [comment]
Actually my previous logic wasn't totally correct either, we further split text into the max tokens supported by the Search models. This is around 250 words which should equate to <500 tokens per result for normal words. We share upto top 5 relevant results with GPT to generate chat response. So that should only result in a max of 2.5k tokens per chat request. 

How are you seeing the OpenAI tokens consumed by Khoj Chat?

It'd be great if you can share the papers you're testing this on, if they're not private. The text splitting may not be working as expected. 

> I tried four queries, but only one worked for me

The Khoj chat timeout issue should be mitigated in the latest pre-release. To try it out, you should upgrade your Khoj server by running `pip install upgrade --pre khoj-assistant` in your terminal.

**Comment by sabaimran** [comment]
I'm going to close this out as improvements we've made to the chat requesting process have reduced risk of timeouts to OpenAI. @wenlzhang , let me know if you run into further issues and I can help debug.
