### ISSUE TITLE
Web UI is not protected with authentication

### ISSUE THREAD

**Issue by link2xt** [khoj-ai/khoj#370]
Jupyter notebook generates a token and uses it to authenticate browser session, so only the user who started the web server process can use the web UI.

With khoj everyone on the same machine with access to http://127.0.0.1:42110/ can change settings to point to index any files (e.g. the whole home directory) and then search it.

**Comment by debanjum** [comment]
Can you describe the scenario in which you trust someone to access your local machine but don't want them to be able change what khoj indexes?

You can start khoj in demo mode with `khoj --demo` if you want to prevent the khoj settings from being modified. This also removes the settings page from the web UI. This is useful if you want to provide folks read access to your khoj over the internet. For example, the [Khoj FAQ website](https://faq.khoj.dev) is configured to work in demo mode

**Comment by davidchisnall** [comment]
> Can you describe the scenario in which you trust someone to access your local machine but don't want them to be able change what khoj indexes?

This is the threat model for any multi-user machine or any machine using any form of privilege separation.  In particular, sandboxed processes that are allowed any network access can connect to localhost and so this is a potential vector for a sandbox escape.  Something like the DHCP client is typically subject to quite a restrictive sandboxing policy, since it handles untrusted packets from random wireless access points, but must be able to initiate network connections.  An attacker who compromises the DHCP client is then able to connect to the settings interface and also leak the contents of documents over the network by querying khol.  

The usual fixes for this are either:

 - Use a UNIX domain socket.  These are subject to file permissions but unfortunately most web browsers don't support a URL schema for describing them.
 - Use some form of authentication.  The simplest thing is, as the original submitter suggested, a random cookie in the URL.  An attacker needs to guess this and if it's something like a base64 encoding of a 128-bit random number then the time taken to guess is infeasible.

**Comment by sabaimran** [comment]
The latest release does enable authentication behind login if Google auth credentials are setup. I think we should also add non-Google/native credentials.

**Comment by debanjum** [comment]
You can require login to your hosted Khoj instance using magic links sent to the users email address. It requires creating a [Resend API Key](https://resend.com/) and setting your `RESEND_API_KEY` environment variable to your API key. It allows authenticating without requiring Google auth or a Gmail address.

Note: Just obfuscating the Khoj web app URL isn't sufficient as the Khoj server API will still be exposed, allowing an attacked to retrieve documents and interact with the user's knowledge base. The Magic Link, Google OAuth auth setups are more involved but follow more standard authentication mechanisms of putting the web app behind authentication
