### ISSUE TITLE
A bug about chat mode output disappearing

### ISSUE THREAD

**Issue by Ellen7ions** [khoj-ai/khoj#382]
When tokens are being output in chat mode, if I switch to search mode and back at that point, the current round of tokens will disappear. 
Is it a bug ?

**Comment by sabaimran** [comment]
Ah, I think this isn't quite a bug. We use chat streaming to send a response to the browser from the LLM. If you change the tab, the connection between the client and server is broken and the request cannot complete.

I think there probably are better ways we can do this, like using sockets that allow us to communicate with the browser without the streamed connection. But for now, this is an expected behavior.
