### ISSUE TITLE
Flatpak release

### ISSUE THREAD

**Issue by Victor239** [khoj-ai/khoj#384]
Would be great to see this available on Flathub for easier installation and auto-updates.

**Comment by putsan** [comment]
Agree!

**Comment by debanjum** [comment]
We've released a new version of Khoj with cleaner client, server separation. As part of it, Khoj has got a new desktop app that's also available as an [AppImage](https://appimage.org/). This is similar to Flatpak. And the new Desktop app will support auto-updates. See the [docs](https://docs.khoj.dev/#/desktop) for setup instructions. 

If you want to self-host the Khoj server (instead of use the Khoj cloud service), you'd need to setup the Khoj server/backend by following these [self-hosting docs](https://docs.khoj.dev/#/setup)

Feel free to re-open this issue, if the `AppImage` release of the Khoj Desktop app isn't good enough for some reason
