### ISSUE TITLE
offline chat generates garbage output

### ISSUE THREAD

**Issue by mtoniott** [khoj-ai/khoj#516]
Hello,

Thank you for this software getting  better everyday.

So recently I updated khoj and the offline chat that was giving me normal answers before is now outputing garbage with Mississipi in it each time for some reasons.
![image](https://github.com/khoj-ai/khoj/assets/54251266/b358e6d6-7ab9-4c0f-842e-87a11a10719a)

I tried reinstalling khoj in a new venv. Did not work.
I tried turning off the offline chat, removing the model in my .cache file then redownload it. Same result.

I guess it is linked to the fact that it wants to use my intel integrated graphics to accelerate the queries. But I did not find a way to turn it off. I get the following line in the terminal;

`llama.cpp: using Vulkan on Intel(R) Iris(R) Plus Graphics 655 (CFL GT3)`

Any idea on how to fix this?

**Comment by debanjum** [comment]
Ah that's unfortunate that you're seeing a regression in behavior. The chat
model being loaded into your GPU could be the reason for this regression
for sure. Let me look into testing this out on my end. Can you share
details of your machine specs. Specifically the RAM, Processor and GPU on
your machine?

### Details

We'd started using an upgraded default model for offline chat (Mistral
instead of Llama 2) and try to use GPU when a (Vulcan) supported GPU is
available on the users machine. Using Intel or AMD GPUs hasn't been tested
as we dont have such machines ourselves.

**Comment by debanjum** [comment]
Ah that's unfortunate that you're seeing a regression in behavior. The chat
model being loaded into your GPU could be the reason for this regression
for sure. Let me look into testing this out on my end. Can you share
details of your machine specs. Specifically the RAM, Processor and GPU on
your machine?


### Details

We'd started using an upgraded default model for offline chat (Mistral
instead of Llama 2) and try to use GPU when a (Vulcan) supported GPU is
available on the users machine. Using Intel or AMD GPUs hasn't been tested
as we dont have such machines ourselves.

**Comment by debanjum** [comment]
Vulkan support in our upstream dependency (GPT4All) still needing some ironing out. Until then I've exposed a CLI flag to allow users to disable using GPU for offline chat. 

To use this fix:
1. Upgrade to the latest pre-release version of Khoj: `pip install --upgrade --pre khoj-assistant`
2. Start Khoj server with `--disable-chat-on-gpu` flag: `khoj --disable-chat-on-gpu`

**Comment by mtoniott** [comment]
It works now. Ty ! 

![image](https://github.com/khoj-ai/khoj/assets/54251266/9d9c1678-4371-4e71-ba7b-d4e048f7be4e)
