### ISSUE TITLE
Emacs: continuously polling for the server

### ISSUE THREAD

**Issue by agzam** [khoj-ai/khoj#567]
Is it possible to implement a configurable max amount of attempts counter after which khoj.el stops polling for the server? When the server is not available, it still keeps trying, polluting the `*Messages*` buffer with errors such as:

```
error in process filter: url-http-activate-callback: Wrong type argument: integer-or-marker-p, " "
error in process filter: Wrong type argument: integer-or-marker-p, " "
error in process filter: url-http-activate-callback: Wrong type argument: integer-or-marker-p, " "
error in process filter: Wrong type argument: integer-or-marker-p, " "
error in process filter: url-http-activate-callback: Wrong type argument: integer-or-marker-p, " "
error in process filter: Wrong type argument: integer-or-marker-p, " "
```

The message also keeps popping up in the echo area, and that's quite distracting.

**Comment by debanjum** [comment]
Hey @agzam, thanks for creating an issue for this!

- I've fixed the bug in error handling of khoj indexer, when server is unavailable. So the `Wrong type argument: integer-or-marker-p` should change to a more reasonable error mentioning that the connection to the server failed.
- If you want to turn off khoj.el from automatically indexing your content, set khoj-auto-index to nil (i.e `setq khoj-auto-index nil`). 
- If you want to change the frequency of indexing you can change `khoj-index-interval` to whatever interval (in seconds) you prefer

Hope that resolves your concerns? Otherwise feel free to re-open this issue
