### ISSUE TITLE
gpt4all missing on docker image?

### ISSUE THREAD

**Issue by bonzofenix** [khoj-ai/khoj#582]
After running docker compose up it fails with the following error: 

<img width="641" alt="Screenshot 2023-12-10 at 14 51 43" src="https://github.com/khoj-ai/khoj/assets/317403/04e4383f-a07b-4c0f-8d81-ca32c3b09f73">

`No module named  'gpt4all'`

**Comment by aswinmohanme** [comment]
I have run into the same bug as well. Running on MacOS.

**Comment by debanjum** [comment]
@bonzofenix are you also on Mac M1+ or a Linux ARM64 machine?

Khoj Offline Chat on ARM64 via Docker is not currently supported because the gpt4all dependency doesn't have an ARM64 build. **You'll need to setup Khoj on your machine locally by [following these instructions](https://docs.khoj.dev/#/setup?id=installation-option-2-local)**.

- Were you hoping to use Khoj with an offline chat model? If so, I'll see if khoj server can start even with gpt4all not installed. So at least search, online chat can work using docker on ARM64 machines
- I'll update the docs to warn about this scenario being unsupported

**Comment by aswinmohanme** [comment]
> @bonzofenix are you also on Mac M1+ or a Linux ARM64 machine?
> 
> Khoj Offline Chat on ARM64 via Docker is not currently supported because the gpt4all dependency doesn't have an ARM64 build. **You'll need to setup Khoj on your machine locally by [following these instructions](https://docs.khoj.dev/#/setup?id=installation-option-2-local)**.
> 
> * Were you hoping to use Khoj with an offline chat model? If so, I'll see if khoj server can start even with gpt4all not installed. So at least search, online chat can work using docker on ARM64 machines
> * I'll update the docs to warn about this scenario being unsupported

Yes, I'm running an M1 Macbook Air. Sorry for not mentioning that in my previous comment.

**Comment by debanjum** [comment]
No issues, thanks for confirming that. The only way around that for now is to install khoj directly on your machine, rather than via docker as mentioned above.
