### ISSUE TITLE
How to access admin when i use my domain?

### ISSUE THREAD

**Issue by oanhcuongdo** [khoj-ai/khoj#608]
I use docker build. I can not access admin because django error domain not in allow_host. Please guide me fix it

**Comment by debanjum** [comment]
What is the domain that your Khoj server is running on?

You can set the `KHOJ_DOMAIN` environment variable to the domain your Khoj server is running on (in your docker-compose.yml or shell from where you start khoj via docker)

**Comment by oanhcuongdo** [comment]
hello, i config as you suggest: - POSTGRES_DB=postgres
      - KHOJ_DOMAIN=mydomain.com
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres but got error:
![khoj-403](https://github.com/khoj-ai/khoj/assets/11918463/f6cde485-3b70-49df-94e9-0f5e98b3a434)

**Comment by sabaimran** [comment]
Hi @oanhcuongdo , are you using Safari? Which browser are you on? Can you try setting `KHOJ_DEBUG=True` in your `docker-compose` and loading from Firefox to see if that helps?

**Comment by uPagge** [comment]
I started docker-compose and got the same problem. I also don't really understand what username to use to access Django

**Comment by uPagge** [comment]
And it really doesn't work in Safari, but it works in Google Chrome

**Comment by Jayddo** [comment]
I am also getting this very same error as in the screenshot, on a mac, on windows, using chromium, firefox and edge.

it wasn't loading the page at all, but by adding KHOJ_DOMAIN I got to a login screen at least. The error happens afterwards. I have tried private tabs as well.

Not sure what else to try. I am running it on linux, unraid, with the sample docker compose

**Comment by sabaimran** [comment]
@Jayddo 
- Are you using Docker, source, or pip for installation?
- Are you able to access the admin screen via localhost? Or does it fail for both localhost and with your custom domain? Do both specifically produce the CSRF verification error?
- Can you make sure that KHOJ_DEBUG is set to false, in case you're trying from your custom domain?

**Comment by Jayddo** [comment]
- not sure on the localhost part, as the docker sits on an unraid server, I can only access it from the unraid ip:42110, which also means the domain I added is actually an ip and not a domain per se, would that be an issue?
- tried setting it false, got the same error without detail

my case is a bit different I suppose due to installing it on unraid. I tried following the instructions and using the sample docker compose, changing volumes to what my actual volumes are.

**Comment by debanjum** [comment]
Is your custom domain behind https? Otherwise this maybe triggered to the CSRF token only being allowed for `KHOJ_DOMAIN` behind an https endpoint. See the `CSRF_TRUSTED_ORIGINS` being set in [settings.py](https://github.com/khoj-ai/khoj/blob/70f74cde683a0777e95baf9e6e85c6327b10009b/src/khoj/app/settings.py#L35)

**Comment by Jayddo** [comment]
Custom domain has a letsencrypt certificate, but it is also available on normal http. I see what you mean, but what can I do about that?
Would it be possible to just... disable this admin login? Khoj sits behind a closed network I can only access via vpn anyway, in my specific case.

**Comment by Jayddo** [comment]
anything I can try or do @sabaimran ?

from the look of things it seems like ssl doesn't work for that particular port/khoj, so I seem to have the CSRF token only allowed behind the https endpoint, as surmised by debanjum.

I would rather disable the backend auth altogether if it's not an easy fix, but I'd be happy to try some more things.

While my setup is non-standard, unraid is very popular so it's probably not going to be uncommon as khoj gets more popular.
