### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by NoIdea147** [khoj-ai/khoj#640]
Since the past month or so, if I wanted to chat with Khoj I'm just getting an error message. "Internal Server Error" 

Steps to reproduce the behavior: I dont think you can reproduce it yourself ... 

## Platform
- Server:
    - [* ] Cloud-Hosted (https://app.khoj.dev)
    - [ ] Self-Hosted Docker
    - [ ] Self-Hosted Python package
    - [ ] Self-Hosted source code
- Client:
    - [ ] Obsidian
    - [ ] Emacs
    - [ ] Desktop app
    - [* ] Web browser
    - [ ] WhatsApp
- OS:
    - [* ] Windows
    - [ ] macOS
    - [ ] Linux
    - [ ] Android
    - [ ] iOS

### If self-hosted
- Server Version [e.g. 1.0.1]:

I also tried to generate new API Keys but nothing worked.

**Comment by sabaimran** [comment]
@NoIdea147 could you shoot me an email with a link to this issue from the email address you use for your Khoj Cloud account at team@khoj.dev? I can try to debug some of these things for you with that.

Otherwise, I think the issue you're running into *might* be due to your indexing model. Can you try deleting all your indexed data (at https://app.khoj.dev/config/content-source/computer), and then try chatting again? If that works, go ahead and push your data again.

**Comment by NoIdea147** [comment]
Thanks mate, this solved the problem :)

sabaimran ***@***.***> schrieb am Mi., 7. Feb. 2024, 11:05:
