### ISSUE TITLE
[FIX] Bad Request (400) running in docker

### ISSUE THREAD

**Issue by techieanant** [khoj-ai/khoj#745]
## Describe the bug
I'm running Khoj docker compose stack on a server on my local network, have all the env variables setup but visiting `/server/admin` route throws a 400 Bad Request error. The logs show the following error: 
```
 DisallowedHost: Invalid HTTP_HOST                    

 header: '10.0.0.197:42110'. You may                  

 need to add '10.0.0.197' to                          

 ALLOWED_HOSTS.
```

There seems to be no way to add a environment variable for setting allowed hosts. 

## To Reproduce
- Run Khoj docker compose stack on a server on your network
- Try to visit the admin route and see error

## Screenshots
<img width="524" alt="image" src="https://github.com/khoj-ai/khoj/assets/7658579/18608cc2-10c6-4399-b290-46e5cba35381">

## Platform
- Server:
    - [ ] Cloud-Hosted (https://app.khoj.dev)
    - [x] Self-Hosted Docker
    - [ ] Self-Hosted Python package
    - [ ] Self-Hosted source code
- Client:
    - [ ] Obsidian
    - [ ] Emacs
    - [ ] Desktop app
    - [x] Web browser
    - [ ] WhatsApp
- OS:
    - [ ] Windows
    - [ ] macOS
    - [x] Linux
    - [ ] Android
    - [ ] iOS

### If self-hosted
- Server Version [e.g. 1.0.1]: 1.12

**Comment by sabaimran** [comment]
Hey @techieanant , I'm assuming you can't access it over `localhost`?

You must have used the `docker-compose.yml` sample file to scaffold you Khoj instance. You can use that to set the environment variable KHOJ_DOMAIN. There are some notes about that here: https://docs.khoj.dev/get-started/setup/#setup-notes.

**Comment by techieanant** [comment]
Thank you that worked although I now see a different problem. 

<img width="1192" alt="image" src="https://github.com/khoj-ai/khoj/assets/7658579/6d9e07c4-808b-4580-a413-5ad42aade7b1">

**Comment by debanjum** [comment]
Hi folks, I was able to verify that the latest Khoj run via Docker does not hit the CSRF or the Bad Request (400) issue when accessing the admin panel. As previously mentioned you need to set the `KHOJ_DOMAIN` environment variable to resolve the Bad Request issue.

I've also simplified the Docker setup in https://github.com/khoj-ai/khoj/pull/919, so configuring Khoj via the admin panel isn't necessary to start using self hosted Khoj.

Do try the latest docker-compose.yml and Khoj docker image to see if the issue is resolved for you? You can see the new [Remote Access Doc](https://docs.khoj.dev/advanced/remote) and the updated [Self Hosting Setup Docs](https://docs.khoj.dev/get-started/setup?os=windows&server=docker) if you're still stuck.

And let me know if you're still hitting the issue, where/how you're running Khoj and client or server console logs to help debug this?
