### ISSUE TITLE
[FIX] Docker-compose up

### ISSUE THREAD

**Issue by JC1738** [khoj-ai/khoj#748]
## Describe the bug
A clear and concise description of what the bug is. Please include what you were expecting to happen vs. what actually happened.

![CleanShot 2024-05-24 at 14 47 25](https://github.com/khoj-ai/khoj/assets/3421783/0ca0e5ce-d8c6-4704-9f85-cdcbcf9896eb)

## To Reproduce

Downloaded the sample docker-compse.yml and updated the user/password and ran docker-compose up

## Platform
- Server:
    - [ ] Cloud-Hosted (https://app.khoj.dev)
    - [ ] Self-Hosted Docker
    - [ ] Self-Hosted Python package
    - [ ] Self-Hosted source code
- Client:
    - [ ] Obsidian
    - [ ] Emacs
    - [ ] Desktop app
    - [ ] Web browser
    - [ ] WhatsApp
- OS:
    - [ ] Windows
    - [ ] macOS
    - [ ] Linux
    - [ ] Android
    - [ ] iOS

### If self-hosted
- Server Version [e.g. 1.0.1]:

**Comment by JC1738** [comment]
I tried two different ubuntu machines (pop and regular) running 22.04 and get the same error.

**Comment by willlee1995** [comment]
Same here for linux NAS. I have not tried building from scratch, I am able to work from my windows host, but not in a NAS linux server. Wondering why the log won't show anything in the docker container even I use --verbose=1 to hopefully get the logger split up some errors.

**Comment by GabrielLanghans** [comment]
Same error here

**Comment by nmathey** [comment]
Same here on Synology NAS: any workaround available yet? 
Should we try specific OS/Arch image https://github.com/khoj-ai/khoj/pkgs/container/khoj?

**Comment by nmathey** [comment]
Ok all docker image are getting the same issue starting release 1.9.0 included.
It might be related to https://github.com/khoj-ai/khoj/pull/680 which sounds link with the error you get in dmesg @ssuukk https://github.com/khoj-ai/khoj/issues/748#issuecomment-2139134293.

@JC1738 maybe we can change the title of this issue to be more precise?

**Comment by sabaimran** [comment]
Hey guys, I'm trying to reproduce this error. I just did a clean install on my Ubuntu 22.04.2 LTS with 16 GB RAM. Do you mind sharing more about your machine specs? Sometimes when docker containers immediately exit like that, it's because of a memory constraint. You can try increasing the allocated memory to the Docker conatiner You can see some [instructions on how to do that here](https://app.khoj.dev/share/chat/how-can-i-increase-the-cpu-or-memory-docker-uses-o) for Linux.

This is happening at first run? Can you try building it again with `KHOJ_DEBUG=True` in your environment variables and see if that gives you anymore info?

**Comment by nmathey** [comment]
Me and @ssuukk trying to make it work on our Synology NAS. I got my self 16G Ram on it but I think the only thing I can do with memory and cpu is limitation which it is not active, so I guess it is getting all ressource it can I guess.

I'll try rebuilding with debug on and let you know.

**Comment by nmathey** [comment]
Since the container stop immediately after few seconds I can't get any logs actually. 
Here are my NAS specs
<img width="591" alt="Capture d’écran 2024-06-09 à 16 24 30" src="https://github.com/khoj-ai/khoj/assets/20896232/bf6a6104-9807-4308-aa66-be98c0cd5138">

**Comment by debanjum** [comment]
Hey folks, I'm closing this issue as:
- It's hard to reproduce without more detailed logs
- It's gone stale as Khoj got a bunch of updates since the issue was opened 4 months ago (including a slicker web UX)

From what I can see, there maybe two different issues being discussed here:
- @JC1738 Given local docker build worked, I wonder if it was some architecture mismatch issue? E.g Khoj docker image built for amd64, your local machine is used some other architecture
- @nmathey, @ssuukk For your issue, the setup of llama.cpp, a Khoj dependency for offline chat, does seem like the primary suspect. Khoj may not work with the Celeron J3455 chipset on your Synology NAS. But I don't have access to a Celeron based machine to reproduce this.

Do try self-host the latest Khoj to see if to works for you all?
I've improved the [self-hosting documentation](https://docs.khoj.dev/get-started/setup?os=linux&server=docker) and Docker setup in #919. So hopefully the setup experience is easier 🤞🏽
