### ISSUE TITLE
[IDEA] Request to Update Documentation and Enhance Local Setup Options for Emacs Client

### ISSUE THREAD

**Issue by Cletip** [khoj-ai/khoj#808]
Hello everyone,

Thank you for the excellent Khoj package, it's truly superb! However, I've encountered an issue while setting it up in Emacs. 

According to the current documentation available at https://docs.khoj.dev/clients/emacs#setup, an API key is required to use the client. I am interested in a fully local solution and would prefer not to use an API key.
In previous versions, it was possible to set up everything locally using the khoj-server-url variable to point to a localhost adress. This was very convenient because the khoj command would set up everything automatically, and I didn't have to do much to get it up and running.

Could you please consider updating the documentation to include information on how to set up Khoj locally without needing an external server? Is there something that I missed ?

Thank you for your attention to this matter.

**Comment by debanjum** [comment]
Hey @Cletip, glad you've been enjoying the Khoj Emacs package!

If you're self-hosting, you do not need an API key to use Khoj from Emacs. You just need to set the `khoj-server-url` to your Khoj server URL. E.g `setq khoj-server-url "http://127.0.0.1:42110"`. I've updated the [documentation](https://docs.khoj.dev/clients/emacs#setup,) to indicate this.

The earlier Khoj Emacs package setup which automatically installed and started the Khoj server is unfortunately deprecated. This is because
- A simple `pip install khoj` isn't sufficient anymore. Khoj needs Postgres DB setup to scale from personal, local setups to multi-user, cloud deployments (like https://app.khoj.dev)
- I didn't have the bandwidth to install and setup postgres from the `khoj.el` Emacs package. Of course, I'm open to contributions to make the Khoj server setup from Emacs easier

Let me know if you have any other concerns? And apologize for the delayed response!
