### ISSUE TITLE
Integrate Langchain processor to include models from all model providers

### ISSUE THREAD

**Issue by ishan00** [khoj-ai/khoj#811]
For Anthropic and OpenAI there are separate classes of functions that use the 3P APIs individually. Using langchain will open up to loads of models with replicable code. 

Wondering why this isn't available already?

Happy to contribute

**Comment by sabaimran** [comment]
Hey @ishan00 ! Our anthropic and openai integrations use the first party libraries. Generalizing to multiple providers is enabled via openai-api compatible proxies like litellm. We're not using langchain because it usually becomes quite constraining if you're using it beyond the basic usage. Thanks for the offer to contribute! But this doesn't need change atm.
