### ISSUE TITLE
I cant change my model

### ISSUE THREAD

**Issue by bayunyoubi** [khoj-ai/khoj#824]
## Describe the bug
I cant change my model,when i change it,i syncs it ,it come back orignal model,internet is no wrong
## To Reproduce
change your model from 4o to 3.5,and sync it

## Screenshots
![image](https://github.com/khoj-ai/khoj/assets/138501273/f1c3496f-c171-4c09-98d0-4cf714b45cb9)
![image](https://github.com/khoj-ai/khoj/assets/138501273/80782470-7d65-44ce-a17b-f7844cf2af98)
![image](https://github.com/khoj-ai/khoj/assets/138501273/8e1bb9b5-9cc7-4c71-a469-b3c69a26ddf0)
![image](https://github.com/khoj-ai/khoj/assets/138501273/90547ea9-95c4-42b6-9fbb-7b2018385220)

- OS:
    - [ ]WINDOW

**Comment by m00nbyt3** [comment]
Just below the selection box, you can read "Subscribe to use different models". So I guess you are not subscribed to any plan. 
It is neccesary to be subscribed in order to be able to change the model. As you can see, Im subscribed and I can see a "Save" option: 
![image](https://github.com/khoj-ai/khoj/assets/34653601/6d886531-8d94-450c-aef0-64804201eb5a)

**Comment by sabaimran** [comment]
@m00nbyt3 is correct, thanks for filling in the relevant context. 

@bayunyoubi , we've made model changing a subscriber-only feature. That's why the option to save isn't present on your settings page.
