### ISSUE TITLE
[FIX] Resend API key not found

### ISSUE THREAD

**Issue by nexty5870** [khoj-ai/khoj#961]
## Describe the bug
Resend not found - same as issue 905, if I removed the anonymous flag and set the environment variable for resend to RESEND_API_KEY= 

The docker doesn't start - I just want magic link for now not GCP

## To Reproduce
remove the anonymous flag - setup resend ENV variable

## Screenshot
![image](https://github.com/user-attachments/assets/53793bd7-4893-478d-b590-2dba9832751a)

## Platform
- Server:
    - [ ] Cloud-Hosted (https://app.khoj.dev)
    - [X] Self-Hosted Docker
    - [ ] Self-Hosted Python package
    - [ ] Self-Hosted source code
- Client:
    - [ ] Obsidian
    - [ ] Emacs
    - [ ] Desktop app
    - [X] Web browser
    - [ ] WhatsApp
- OS:
    - [ ] Windows
    - [ ] macOS
    - [X] Linux
    - [ ] Android
    - [ ] iOS

### If self-hosted
- Server Version [e.g. 1.0.1]:

## Additional context
Resend not found previous issue - https://github.com/khoj-ai/khoj/issues/905

**Comment by sabaimran** [comment]
Hi @nexty5870 , we don't include the resend package in the normal docker image. You'll want to use the prod docker image -- `ghcr.io/khoj-ai/khoj-cloud:latest`. 

Do you mind sharing what you're using it for? Is it for automations, sign-in, are you using it for the multi-user scenario?

**Comment by CamLamb** [comment]
I'm also experiencing this issue. I have setup resend as per the documentation here:
https://docs.khoj.dev/advanced/authentication/

I have tried switching images by changing the image referenced in my `docker-compose.yml`.
However, this doesn't seem to work and the only thing I can see in my logs for the container is:

```
gunicorn (version 22.0.0)
```

Looking in portainer, I can see that the container failed with an exit code of `0`.
I guessed that this meant my `command` in the docker compose file was incorrect so I commented that out and tried it again.

This launched the app successfully! But when I try to log in, I get an alert in my browser `Failed to send magic link`.

Looking at the logs I see:
```
resend.exceptions.ResendError: The khoj.dev domain is not verified. Please, add and verify your domain on https://resend.com/domains
```
This tells me that the image you suggest we use doesn't respect the environment variables set in my docker compose file.

-----

Given all of the above I feel like maybe the resend package should be available in the normal docker image. This will mean that people like myself are able to get things working as documented.

**Comment by sabaimran** [comment]
Ahh @CamLamb , thanks for raising that point and the detailed logs. You're right, there's an issue here in that our code still sets the outgoing emails as `team@khoj.dev` for all the welcome emails -- [see here](https://github.com/khoj-ai/khoj/blob/master/src/khoj/routers/email.py#L56). Of course, that won't work if you have your own Resend account, which is not connected to our khoj.dev domain.

Sorry we didn't catch this sooner. We haven't had too many people using the self-hosted setup with email login. I'm still inclined to keep the resend integration in the `prod` images, because the prod setup is more intended for multi-user hosting. Implicitly, anyone using email sign-in is probably running a multi-user setup.

I'll update the documentation and add an environment variables so you can set a custom `from` address in the outgoing emails.

**Comment by sabaimran** [comment]
Docs have been updated! https://docs.khoj.dev/advanced/authentication/#using-magic-links

**Comment by sabaimran** [comment]
I'm going to close this issue out as both the original and follow-up issues seem to be addressed with documentation, but feel free to follow-up in case there's further requests!
